"""Add Domain models

Revision ID: 2032349c4e13
Revises: f66fc3e39df1
Create Date: 2026-07-25 01:45:37.727856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2032349c4e13'
down_revision: Union[str, Sequence[str], None] = 'f66fc3e39df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_domains',
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_college_domains_domain'), 'college_domains', ['domain'], unique=True)
    op.create_index(op.f('ix_college_domains_id'), 'college_domains', ['id'], unique=False)
    op.add_column('colleges', sa.Column('subscription', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('storage_limit', sa.Integer(), nullable=True))
    op.add_column('colleges', sa.Column('storage_used', sa.Integer(), nullable=True))
    op.drop_column('colleges', 'primary_color')
    op.drop_column('colleges', 'academic_year')
    op.drop_column('colleges', 'email')
    op.drop_column('colleges', 'storage_used_mb')
    op.drop_column('colleges', 'city')
    op.drop_column('colleges', 'storage_limit_gb')
    op.drop_column('colleges', 'timezone')
    op.drop_column('colleges', 'country')
    op.drop_column('colleges', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colleges', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('storage_limit_gb', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('storage_used_mb', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('colleges', sa.Column('academic_year', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('primary_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('colleges', 'storage_used')
    op.drop_column('colleges', 'storage_limit')
    op.drop_column('colleges', 'subscription')
    op.drop_index(op.f('ix_college_domains_id'), table_name='college_domains')
    op.drop_index(op.f('ix_college_domains_domain'), table_name='college_domains')
    op.drop_table('college_domains')
    # ### end Alembic commands ###
