"""update college fields

Revision ID: 551ab44a2375
Revises: 2032349c4e13
Create Date: 2026-07-25 13:24:18.756372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551ab44a2375'
down_revision: Union[str, Sequence[str], None] = '2032349c4e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colleges', sa.Column('institution_type', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('established_year', sa.Integer(), nullable=True))
    op.add_column('colleges', sa.Column('affiliation', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('accreditation', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('official_email', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('country', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('state', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('city', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('pin_code', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('full_address', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('colleges', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colleges', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('colleges', 'status')
    op.drop_column('colleges', 'full_address')
    op.drop_column('colleges', 'pin_code')
    op.drop_column('colleges', 'city')
    op.drop_column('colleges', 'state')
    op.drop_column('colleges', 'country')
    op.drop_column('colleges', 'official_email')
    op.drop_column('colleges', 'accreditation')
    op.drop_column('colleges', 'affiliation')
    op.drop_column('colleges', 'established_year')
    op.drop_column('colleges', 'institution_type')
    # ### end Alembic commands ###
