"""Add User section and ClassroomResource model

Revision ID: e83af88ff00e
Revises: 551ab44a2375
Create Date: 2026-07-28 17:02:44.670883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83af88ff00e'
down_revision: Union[str, Sequence[str], None] = '551ab44a2375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_resources',
    sa.Column('classroom_code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.String(), nullable=False),
    sa.Column('target_section', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_resources_classroom_code'), 'classroom_resources', ['classroom_code'], unique=False)
    op.create_index(op.f('ix_classroom_resources_id'), 'classroom_resources', ['id'], unique=False)
    op.add_column('users', sa.Column('section', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'section')
    op.drop_index(op.f('ix_classroom_resources_id'), table_name='classroom_resources')
    op.drop_index(op.f('ix_classroom_resources_classroom_code'), table_name='classroom_resources')
    op.drop_table('classroom_resources')
    # ### end Alembic commands ###
